# Generated by Django 4.2 on 2023-04-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, unique=True)),
                ('password', models.CharField(max_length=24)),
                ('type', models.CharField(choices=[('A', 'Administrator'), ('T', 'Tester'), ('P', 'Programmer')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('API.employee',),
        ),
        migrations.CreateModel(
            name='Programmer',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('API.employee',),
        ),
        migrations.CreateModel(
            name='Tester',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('API.employee',),
        ),
    ]
