# Generated by Django 4.2 on 2023-04-21 18:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_remove_employee_session_employeesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
