# Generated by Django 4.2 on 2023-04-22 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_alter_employee_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=64)),
                ('status', models.CharField(default='unassigned', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_bugs', to='API.tester')),
                ('solver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_to_solve', to='API.programmer')),
            ],
        ),
    ]
