# Generated by Django 4.2 on 2023-04-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_bug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='bug',
            name='solver',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bugs_to_solve', to='API.programmer'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
