# Generated by Django 4.2 on 2023-04-23 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_bug_description_alter_bug_solver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='solver',
            new_name='assigned_to',
        ),
        migrations.AddField(
            model_name='bug',
            name='solved_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solved_bugs', to='API.programmer'),
        ),
    ]
