USE S11;
GO

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ -- phantom reads
-- SET TRANSACTION ISOLATION LEVEL SERIALIZABLE -- phantom reads solutions
BEGIN TRAN;
SELECT * FROM Tablouri WHERE Tid = (SELECT MAX(Tid) FROM Tablouri);
WAITFOR DELAY '00:00:05';
SELECT * FROM Tablouri WHERE Tid = (SELECT MAX(Tid) FROM Tablouri);
COMMIT TRAN;
